const path = require('path');
const crypto = require('crypto');
const { pagination, pageResult, TTLCache } = require('./performance-utils');

let connection;
const dashboardCache = new TTLCache(30_000);

function filePath() { return process.env.MIDO_ACCESS_FILE || path.join(__dirname, 'data', 'mido-demo.accdb'); }
function connectionString() { const file = filePath().replace(/\\/g, '\\\\'); return process.env.MIDO_ACCESS_CONNECTION_STRING || `Driver={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=${file};`; }
async function getConnection() {
  if (connection) return connection;
  let odbc;
  try { odbc = require('odbc'); } catch (_) { throw new Error('حزمة odbc غير مثبتة. نفّذ npm ci على Windows.'); }
  try { connection = await odbc.connect(connectionString()); return connection; }
  catch (error) { throw new Error(`تعذر فتح قاعدة Access: ${error.message}`); }
}
async function query(sql, params = []) { return (await (await getConnection()).query(sql, params)) || []; }
function ctx(input = {}) { return { companyId: Number(input.COMPANY_ID || input.companyId || 1), branchId: Number(input.BRANCH_ID || input.branchId || 1), fiscalYearId: Number(input.FISCAL_YEAR_ID || input.fiscalYearId || 1) }; }
function normalizeSearch(value) { return `%${String(value || '').trim()}%`; }
function verifyPassword(password, stored) {
  const [algorithm, iterations, salt, expected] = String(stored || '').split('$');
  if (algorithm !== 'pbkdf2' || !iterations || !salt || !expected) return false;
  const actual = crypto.pbkdf2Sync(String(password), salt, Number(iterations), 32, 'sha256').toString('base64url');
  return crypto.timingSafeEqual(Buffer.from(actual), Buffer.from(expected));
}
async function test() { const rows = await query('SELECT 1 AS CONNECTION_OK'); return { engine: 'access', connected: true, ...rows[0] }; }
async function dashboard(input = {}) {
  const scope = ctx(input); const key = `dashboard:${scope.companyId}:${scope.branchId}:${scope.fiscalYearId}`; const cached = dashboardCache.get(key); if (cached) return { ...cached, cached: true };
  const [accounts, contacts, journals] = await Promise.all([query('SELECT COUNT(*) AS COUNT FROM ONYX_ACCOUNT WHERE COMPANY_ID=?', [scope.companyId]), query('SELECT COUNT(*) AS COUNT FROM ONYX_CONTACT WHERE COMPANY_ID=?', [scope.companyId]), query('SELECT COUNT(*) AS COUNT FROM ONYX_JOURNAL_ENTRY WHERE COMPANY_ID=? AND BRANCH_ID=?', [scope.companyId, scope.branchId])]);
  return dashboardCache.set(key, { mode: 'access', accounts: accounts[0].COUNT, customers: contacts[0].COUNT, journals: journals[0].COUNT });
}
async function modernAccounts(search = '') { return query('SELECT TOP 250 ACCOUNT_ID,ACCOUNT_CODE,ACCOUNT_NAME_AR,ACCOUNT_TYPE,PARENT_CODE,OPENING_BALANCE,ACTIVE_FLAG FROM ONYX_ACCOUNT WHERE COMPANY_ID=? AND (ACCOUNT_CODE LIKE ? OR ACCOUNT_NAME_AR LIKE ?) ORDER BY ACCOUNT_CODE', [1, normalizeSearch(search), normalizeSearch(search)]); }
async function modernContacts(input = '') { const p = typeof input === 'string' ? { search: input } : input; const scope = ctx(p.context); const { page, pageSize, offset } = pagination(p); const rows = await query('SELECT CONTACT_ID,CONTACT_TYPE,CODE,NAME_AR,PHONE,EMAIL,TAX_NUMBER,CREDIT_LIMIT,ACTIVE_FLAG FROM ONYX_CONTACT WHERE COMPANY_ID=? AND (CODE LIKE ? OR NAME_AR LIKE ?) ORDER BY CONTACT_TYPE,CODE', [scope.companyId, normalizeSearch(p.search), normalizeSearch(p.search)]); if (p.page == null && p.pageSize == null) return rows.slice(0, 250); return pageResult(rows.slice(offset, offset + pageSize), page, pageSize, rows.length); }
async function modernItems(input = '') { const p = typeof input === 'string' ? { search: input } : input; const scope = ctx(p.context); const { page, pageSize, offset } = pagination(p); const rows = await query('SELECT ITEM_ID,ITEM_CODE,ITEM_NAME_AR,UNIT_NAME,COST_PRICE,SALE_PRICE,QUANTITY,REORDER_LEVEL,ACTIVE_FLAG FROM ONYX_ITEM WHERE COMPANY_ID=? AND (ITEM_CODE LIKE ? OR ITEM_NAME_AR LIKE ?) ORDER BY ITEM_CODE', [scope.companyId, normalizeSearch(p.search), normalizeSearch(p.search)]); if (p.page == null && p.pageSize == null) return rows.slice(0, 250); return pageResult(rows.slice(offset, offset + pageSize), page, pageSize, rows.length); }
async function createModernAccount(p = {}) { const scope = ctx(p.context); await query('INSERT INTO ONYX_ACCOUNT (COMPANY_ID,ACCOUNT_CODE,ACCOUNT_NAME_AR,ACCOUNT_TYPE,PARENT_CODE,OPENING_BALANCE,ACTIVE_FLAG) VALUES (?,?,?,?,?,?,1)', [scope.companyId, p.code, p.name, p.type || 'GENERAL', p.parentCode || null, Number(p.openingBalance || 0)]); return { code: p.code, name: p.name }; }
async function createModernContact(p = {}) { const scope = ctx(p.context); await query('INSERT INTO ONYX_CONTACT (COMPANY_ID,CONTACT_TYPE,CODE,NAME_AR,PHONE,EMAIL,TAX_NUMBER,ACTIVE_FLAG) VALUES (?,?,?,?,?,?,?,1)', [scope.companyId, p.type === 'VENDOR' ? 'VENDOR' : 'CUSTOMER', p.code, p.name, p.phone || null, p.email || null, p.taxNumber || null]); return { code: p.code, name: p.name, type: p.type || 'CUSTOMER' }; }
async function createModernItem(p = {}) { const scope = ctx(p.context); await query('INSERT INTO ONYX_ITEM (COMPANY_ID,ITEM_CODE,ITEM_NAME_AR,UNIT_NAME,COST_PRICE,SALE_PRICE,QUANTITY,REORDER_LEVEL,ACTIVE_FLAG) VALUES (?,?,?,?,?,?,?,?,1)', [scope.companyId, p.code, p.name, p.unit || 'قطعة', Number(p.cost || 0), Number(p.sale || 0), Number(p.quantity || 0), Number(p.reorder || 0)]); return { code: p.code, name: p.name }; }
async function createModernInvoice(p = {}) { const scope = ctx(p.context); const lines = Array.isArray(p.lines) ? p.lines : []; const subtotal = lines.reduce((sum, line) => sum + Number(line.quantity || 0) * Number(line.unitPrice || 0), 0); const tax = Number(p.taxAmount || 0); const total = subtotal + tax; const no = p.invoiceNo || `INV-${Date.now()}`; await query('INSERT INTO ONYX_INVOICE (COMPANY_ID,BRANCH_ID,FISCAL_YEAR_ID,INVOICE_TYPE,INVOICE_NO,CONTACT_ID,SUBTOTAL,TAX_AMOUNT,TOTAL_AMOUNT,PAID_AMOUNT,OUTSTANDING_AMOUNT,STATUS_CODE,CURRENCY_CODE,EXCHANGE_RATE,INVOICE_DATE) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', [scope.companyId, scope.branchId, scope.fiscalYearId, p.type === 'PURCHASE' ? 'PURCHASE' : 'SALE', no, null, subtotal, tax, total, Number(p.paidAmount || 0), total - Number(p.paidAmount || 0), 'DRAFT', p.currency || 'SAR', Number(p.exchangeRate || 1), p.invoiceDate ? new Date(p.invoiceDate) : new Date()]); return { invoiceId: null, invoiceNo: no, status: 'DRAFT', totalAmount: total }; }
async function listInvoices(p = {}) { const scope = ctx(p.context); const { page, pageSize, offset } = pagination(p); const rows = await query('SELECT i.INVOICE_ID,i.INVOICE_NO,i.INVOICE_TYPE,i.INVOICE_DATE,i.SUBTOTAL,i.TAX_AMOUNT,i.TOTAL_AMOUNT,i.PAID_AMOUNT,i.OUTSTANDING_AMOUNT,i.STATUS_CODE,i.CURRENCY_CODE,i.EXCHANGE_RATE FROM ONYX_INVOICE i WHERE i.COMPANY_ID=? AND i.BRANCH_ID=? AND (?=0 OR i.FISCAL_YEAR_ID=?) AND (? IS NULL OR i.INVOICE_TYPE=?) ORDER BY i.INVOICE_DATE DESC,i.INVOICE_ID DESC', [scope.companyId, scope.branchId, scope.fiscalYearId || 0, scope.fiscalYearId || 0, p.invoiceType || null, p.invoiceType || null]); if (p.page == null && p.pageSize == null) return rows.slice(0, Math.min(Number(p.limit) || 100, 500)); return pageResult(rows.slice(offset, offset + pageSize), page, pageSize, rows.length); }
async function globalSearch(p = {}) { const q = String(p.search || '').trim(); if (q.length < 2) return { contacts: [], items: [], invoices: [] }; const scope = ctx(p.context); const like = normalizeSearch(q); const limit = Math.min(Math.max(Number(p.limit) || 8, 1), 25); const [contacts, items, invoices] = await Promise.all([query('SELECT TOP 25 CONTACT_ID,CODE,NAME_AR,CONTACT_TYPE FROM ONYX_CONTACT WHERE COMPANY_ID=? AND (CODE LIKE ? OR NAME_AR LIKE ?) ORDER BY CODE', [scope.companyId, like, like]), query('SELECT TOP 25 ITEM_ID,ITEM_CODE,ITEM_NAME_AR,QUANTITY FROM ONYX_ITEM WHERE COMPANY_ID=? AND (ITEM_CODE LIKE ? OR ITEM_NAME_AR LIKE ?) ORDER BY ITEM_CODE', [scope.companyId, like, like]), query('SELECT TOP 25 INVOICE_ID,INVOICE_NO,INVOICE_TYPE,TOTAL_AMOUNT,STATUS_CODE FROM ONYX_INVOICE WHERE COMPANY_ID=? AND BRANCH_ID=? AND INVOICE_NO LIKE ? ORDER BY INVOICE_DATE DESC', [scope.companyId, scope.branchId, like])]); return { contacts: contacts.slice(0, limit), items: items.slice(0, limit), invoices: invoices.slice(0, limit) }; }
async function authenticate(username, password) { const rows = await query('SELECT TOP 1 USER_ID,USERNAME,DISPLAY_NAME_AR,PASSWORD_HASH,ACTIVE_FLAG FROM ONYX_USER WHERE USERNAME=?', [username]); const user = rows[0]; if (!user || !user.ACTIVE_FLAG || !verifyPassword(password, user.PASSWORD_HASH)) throw new Error('اسم المستخدم أو كلمة المرور غير صحيحة.'); return { userId: user.USER_ID, username: user.USERNAME, displayNameAr: user.DISPLAY_NAME_AR, permissions: ['ALL'], context: { COMPANY_ID: 1, BRANCH_ID: 1, FISCAL_YEAR_ID: 1 } }; }
async function listUsers() { return query('SELECT USER_ID,USERNAME,DISPLAY_NAME_AR,ACTIVE_FLAG FROM ONYX_USER ORDER BY USERNAME'); }
async function listRoles() { return query('SELECT ROLE_ID,ROLE_CODE,ROLE_NAME_AR FROM ONYX_ROLE ORDER BY ROLE_CODE'); }
async function recordAudit(p = {}) { await query('INSERT INTO ONYX_AUDIT_LOG (USERNAME,ACTION_CODE,ENTITY_NAME,ENTITY_ID,CREATED_AT) VALUES (?,?,?,?,?)', [p.username || null, p.actionCode || 'UNKNOWN', p.entityType || null, String(p.entityId || ''), new Date()]); return true; }
async function listAudit(p = {}) { return query('SELECT TOP 200 AUDIT_ID,USERNAME,ACTION_CODE,ENTITY_NAME,ENTITY_ID,CREATED_AT FROM ONYX_AUDIT_LOG ORDER BY CREATED_AT DESC'); }
async function close() { if (connection) { await connection.close(); connection = undefined; } }
function unsupported(name) { return async () => { throw new Error(`العملية ${name} غير متاحة بعد في محرك Access.`); }; }
const api = { test, dashboard, modernAccounts, modernContacts, modernItems, createModernAccount, createModernContact, createModernItem, createModernInvoice, listInvoices, globalSearch, authenticate, listUsers, listRoles, recordAudit, listAudit, close };
for (const name of ['accounts','customers','journal','financialReports','trialBalanceReport','generalLedgerReport','incomeStatementReport','balanceSheetReport','salesPurchaseReport','inventoryValuationReport','createModernJournal','transitionInvoice','listWarehouses','listStockMovements','listTradeDocuments','createTradeDocument','transitionTradeDocument','createCashVoucher','listCashVouchers','updateCashVoucher','voidCashVoucher','createExpenseIncome','listExpenseIncome','updateExpenseIncome','voidExpenseIncome','createReceivablePayment','postReceivablePayment','listReceivablePayments','receivablesAgingReport','listFiscalPeriods','precheckFiscalPeriodClose','closeFiscalPeriod','reopenFiscalPeriod','listPeriodCloseHistory','createUser','assignRole','listSessionContexts','setSessionContext']) api[name] = unsupported(name);
module.exports = api;
