const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('onyxAPI', {
  setupTestConnection: (payload) => ipcRenderer.invoke('db:setup-test', payload),
  setupInspectSchema: (payload) => ipcRenderer.invoke('db:setup-inspect', payload),
  setupInitializeSchema: (payload) => ipcRenderer.invoke('db:setup-initialize', payload),
  dbTest: () => ipcRenderer.invoke('db:test'),
  dashboard: () => ipcRenderer.invoke('db:dashboard'),
  accounts: (search = '') => ipcRenderer.invoke('db:accounts', { search }),
  modernAccounts: (search = '') => ipcRenderer.invoke('db:modern-accounts', { search }),
  createAccount: (payload) => ipcRenderer.invoke('db:create-account', payload),
  modernContacts: (search = '') => ipcRenderer.invoke('db:modern-contacts', { search }),
  createContact: (payload) => ipcRenderer.invoke('db:create-contact', payload),
  modernItems: (search = '') => ipcRenderer.invoke('db:modern-items', { search }),
  createItem: (payload) => ipcRenderer.invoke('db:create-item', payload),
  createInvoice: (payload) => ipcRenderer.invoke('db:create-invoice', payload),
  approveInvoice: (payload) => ipcRenderer.invoke('db:approve-invoice', payload),
  recordPayment: (payload) => ipcRenderer.invoke('db:record-payment', payload),
  createInvoiceReturn: (payload) => ipcRenderer.invoke('db:create-return', payload),
  createTradeDocument: (payload) => ipcRenderer.invoke('documents:create', payload),
  listTradeDocuments: (payload = {}) => ipcRenderer.invoke('documents:list', payload),
  transitionTradeDocument: (payload) => ipcRenderer.invoke('documents:transition', payload),
  customers: (search = '') => ipcRenderer.invoke('db:customers', { search }),
  journal: (limit = 50) => ipcRenderer.invoke('db:journal', { limit }),
  financialReports: (payload = {}) => ipcRenderer.invoke('reports:financial', payload),
  auditEvents: (payload = {}) => ipcRenderer.invoke('admin:list-audit', payload),
  createJournal: (payload) => ipcRenderer.invoke('db:create-journal', payload),
  currentSession: () => ipcRenderer.invoke('auth:current'),
  licenseStatus: () => ipcRenderer.invoke('auth:license'),
  sessionContexts: () => ipcRenderer.invoke('auth:contexts'),
  setSessionContext: (payload) => ipcRenderer.invoke('auth:set-context', payload),
  login: (payload) => ipcRenderer.invoke('auth:login', payload),
  logout: () => ipcRenderer.invoke('auth:logout'),
  hasUsers: () => ipcRenderer.invoke('admin:has-users'),
  listUsers: () => ipcRenderer.invoke('admin:list-users'),
  listRoles: () => ipcRenderer.invoke('admin:list-roles'),
  createUser: (payload) => ipcRenderer.invoke('admin:create-user', payload),
  assignRole: (payload) => ipcRenderer.invoke('admin:assign-role', payload),
  listAudit: (payload = {}) => ipcRenderer.invoke('admin:list-audit', payload),
});
