const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('onyxAPI', {
  setupTestConnection: (payload) => ipcRenderer.invoke('db:setup-test', payload),
  setupInspectSchema: (payload) => ipcRenderer.invoke('db:setup-inspect', payload),
  setupInitializeSchema: (payload) => ipcRenderer.invoke('db:setup-initialize', payload),
  dbTest: () => ipcRenderer.invoke('db:test'),
  dashboard: () => ipcRenderer.invoke('db:dashboard'),
  accounts: (search = '') => ipcRenderer.invoke('db:accounts', { search }),
  modernAccounts: (search = '') => ipcRenderer.invoke('db:modern-accounts', { search }),
  createAccount: (payload) => ipcRenderer.invoke('db:create-account', payload),
  modernContacts: (search = '') => ipcRenderer.invoke('db:modern-contacts', { search }),
  createContact: (payload) => ipcRenderer.invoke('db:create-contact', payload),
  modernItems: (search = '') => ipcRenderer.invoke('db:modern-items', { search }),
  createItem: (payload) => ipcRenderer.invoke('db:create-item', payload),
  createInvoice: (payload) => ipcRenderer.invoke('db:create-invoice', payload),
  listInvoices: (payload = {}) => ipcRenderer.invoke('invoices:list', payload),
  listWarehouses: (payload = {}) => ipcRenderer.invoke('inventory:warehouses', payload),
  listStockMovements: (payload = {}) => ipcRenderer.invoke('inventory:movements', payload),
  previewBusinessOperation: (payload) => ipcRenderer.invoke('business:preview', payload),
  listCashVouchers: (payload = {}) => ipcRenderer.invoke('cash-vouchers:list', payload),
  createCashVoucher: (payload) => ipcRenderer.invoke('cash-vouchers:create', payload),
  updateCashVoucher: (payload) => ipcRenderer.invoke('cash-vouchers:update', payload),
  voidCashVoucher: (payload) => ipcRenderer.invoke('cash-vouchers:void', payload),
  listExpenseIncome: (payload = {}) => ipcRenderer.invoke('expense-income:list', payload),
  createExpenseIncome: (payload) => ipcRenderer.invoke('expense-income:create', payload),
  updateExpenseIncome: (payload) => ipcRenderer.invoke('expense-income:update', payload),
  voidExpenseIncome: (payload) => ipcRenderer.invoke('expense-income:void', payload),
  createTradeDocument: (payload) => ipcRenderer.invoke('documents:create', payload),
  listTradeDocuments: (payload = {}) => ipcRenderer.invoke('documents:list', payload),
  transitionTradeDocument: (payload) => ipcRenderer.invoke('documents:transition', payload),
  customers: (search = '') => ipcRenderer.invoke('db:customers', { search }),
  journal: (limit = 50) => ipcRenderer.invoke('db:journal', { limit }),
  financialReports: (payload = {}) => ipcRenderer.invoke('reports:financial', payload),
  trialBalanceReport: (payload = {}) => ipcRenderer.invoke('reports:trial-balance', payload),
  generalLedgerReport: (payload = {}) => ipcRenderer.invoke('reports:general-ledger', payload),
  incomeStatementReport: (payload = {}) => ipcRenderer.invoke('reports:income-statement', payload),
  balanceSheetReport: (payload = {}) => ipcRenderer.invoke('reports:balance-sheet', payload),
  salesPurchaseReport: (payload = {}) => ipcRenderer.invoke('reports:sales-purchase', payload),
  inventoryValuationReport: (payload = {}) => ipcRenderer.invoke('reports:inventory-valuation', payload),
  auditEvents: (payload = {}) => ipcRenderer.invoke('admin:list-audit', payload),
  createJournal: (payload) => ipcRenderer.invoke('db:create-journal', payload),
  currentSession: () => ipcRenderer.invoke('auth:current'),
  sessionContexts: () => ipcRenderer.invoke('auth:contexts'),
  setSessionContext: (payload) => ipcRenderer.invoke('auth:set-context', payload),
  login: (payload) => ipcRenderer.invoke('auth:login', payload),
  logout: () => ipcRenderer.invoke('auth:logout'),
  hasUsers: () => ipcRenderer.invoke('admin:has-users'),
  listUsers: () => ipcRenderer.invoke('admin:list-users'),
  listRoles: () => ipcRenderer.invoke('admin:list-roles'),
  createUser: (payload) => ipcRenderer.invoke('admin:create-user', payload),
  assignRole: (payload) => ipcRenderer.invoke('admin:assign-role', payload),
  listAudit: (payload = {}) => ipcRenderer.invoke('admin:list-audit', payload),
});
