-- Commercial invoice workflow: approvals, partial payments, returns and read-only-safe audit trail
alter session set container=XEPDB1;

alter table onyx_invoice add (
  payment_method varchar2(20) default 'CREDIT' not null,
  payment_status varchar2(20) default 'UNPAID' not null,
  due_date date,
  paid_amount number(24,3) default 0 not null,
  approval_status varchar2(24) default 'NOT_REQUIRED' not null,
  approved_by number references onyx_user(user_id),
  approved_at timestamp,
  return_of_invoice_id number references onyx_invoice(invoice_id)
);

alter table onyx_invoice add constraint ck_onyx_invoice_payment_method check(payment_method in ('CASH','BANK','CARD','E_WALLET','CREDIT'));
alter table onyx_invoice add constraint ck_onyx_invoice_payment_status check(payment_status in ('PAID','PARTIAL','UNPAID'));
alter table onyx_invoice add constraint ck_onyx_invoice_approval check(approval_status in ('NOT_REQUIRED','PENDING','APPROVED','REJECTED'));
alter table onyx_invoice add constraint ck_onyx_invoice_paid check(paid_amount >= 0 and paid_amount <= total_amount);

create table onyx_invoice_payment (
  payment_id number generated by default as identity primary key,
  invoice_id number not null references onyx_invoice(invoice_id),
  company_id number not null references onyx_company(company_id),
  branch_id number not null references onyx_branch(branch_id),
  payment_date date default trunc(sysdate) not null,
  amount number(24,3) not null,
  payment_method varchar2(20) not null,
  reference_no varchar2(80),
  journal_entry_id number references onyx_journal_entry(entry_id),
  created_by number references onyx_user(user_id),
  created_at timestamp default systimestamp not null,
  constraint ck_onyx_payment_amount check(amount > 0),
  constraint ck_onyx_payment_method check(payment_method in ('CASH','BANK','CARD','E_WALLET'))
);

create table onyx_invoice_return (
  return_id number generated by default as identity primary key,
  invoice_id number not null references onyx_invoice(invoice_id),
  return_invoice_id number not null references onyx_invoice(invoice_id),
  company_id number not null references onyx_company(company_id),
  reason varchar2(500),
  created_by number references onyx_user(user_id),
  created_at timestamp default systimestamp not null,
  constraint uq_onyx_invoice_return unique(invoice_id, return_invoice_id)
);

create index ix_onyx_invoice_payment_invoice on onyx_invoice_payment(invoice_id, payment_date);
create index ix_onyx_invoice_return_source on onyx_invoice_return(invoice_id);
create index ix_onyx_invoice_approval on onyx_invoice(company_id, approval_status, status_code);

create or replace view onyx_invoice_balance_v as
select i.invoice_id, i.company_id, i.branch_id, i.invoice_type, i.invoice_no,
       i.total_amount, nvl(sum(p.amount),0) paid_amount,
       greatest(i.total_amount - nvl(sum(p.amount),0),0) balance_due,
       i.payment_status, i.approval_status, i.due_date
  from onyx_invoice i
  left join onyx_invoice_payment p on p.invoice_id=i.invoice_id
 group by i.invoice_id, i.company_id, i.branch_id, i.invoice_type, i.invoice_no,
          i.total_amount, i.payment_status, i.approval_status, i.due_date;

commit;
exit;
