-- Mido performance indexes, migration 017
-- Run after migrations 001-016 as ONYX_APP.

DECLARE
  PROCEDURE ensure_index(p_name VARCHAR2, p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -955 THEN RAISE; END IF;
  END;
BEGIN
  ensure_index('IX_ONYX_CONTACT_SCOPE_CODE', 'CREATE INDEX IX_ONYX_CONTACT_SCOPE_CODE ON ONYX_CONTACT (COMPANY_ID, CONTACT_TYPE, CODE)');
  ensure_index('IX_ONYX_CONTACT_SCOPE_NAME', 'CREATE INDEX IX_ONYX_CONTACT_SCOPE_NAME ON ONYX_CONTACT (COMPANY_ID, NAME_AR)');
  ensure_index('IX_ONYX_ITEM_SCOPE_CODE', 'CREATE INDEX IX_ONYX_ITEM_SCOPE_CODE ON ONYX_ITEM (COMPANY_ID, ITEM_CODE)');
  ensure_index('IX_ONYX_ITEM_SCOPE_NAME', 'CREATE INDEX IX_ONYX_ITEM_SCOPE_NAME ON ONYX_ITEM (COMPANY_ID, ITEM_NAME_AR)');
  ensure_index('IX_ONYX_INV_SCOPE_DATE_STATUS', 'CREATE INDEX IX_ONYX_INV_SCOPE_DATE_STATUS ON ONYX_INVOICE (COMPANY_ID, BRANCH_ID, INVOICE_DATE, STATUS_CODE, INVOICE_ID)');
  ensure_index('IX_ONYX_INV_SCOPE_TYPE', 'CREATE INDEX IX_ONYX_INV_SCOPE_TYPE ON ONYX_INVOICE (COMPANY_ID, BRANCH_ID, INVOICE_TYPE, STATUS_CODE)');
  ensure_index('IX_ONYX_TRADE_SCOPE_DATE', 'CREATE INDEX IX_ONYX_TRADE_SCOPE_DATE ON ONYX_TRADE_DOCUMENT (COMPANY_ID, BRANCH_ID, DOCUMENT_DATE, STATUS_CODE, DOCUMENT_ID)');
  ensure_index('IX_ONYX_STOCK_ITEM_WH_DATE', 'CREATE INDEX IX_ONYX_STOCK_ITEM_WH_DATE ON ONYX_STOCK_MOVEMENT (ITEM_ID, WAREHOUSE_ID, MOVEMENT_DATE)');
  ensure_index('IX_ONYX_JE_SCOPE_DATE_STATUS', 'CREATE INDEX IX_ONYX_JE_SCOPE_DATE_STATUS ON ONYX_JOURNAL_ENTRY (COMPANY_ID, BRANCH_ID, FISCAL_YEAR_ID, ENTRY_DATE, STATUS_CODE)');
  ensure_index('IX_ONYX_AUDIT_SCOPE_DATE', 'CREATE INDEX IX_ONYX_AUDIT_SCOPE_DATE ON ONYX_AUDIT_LOG (COMPANY_ID, BRANCH_ID, CREATED_AT, ENTITY_TYPE)');
  ensure_index('IX_ONYX_AR_PAYMENT_SCOPE_DATE', 'CREATE INDEX IX_ONYX_AR_PAYMENT_SCOPE_DATE ON ONYX_AR_PAYMENT (COMPANY_ID, BRANCH_ID, PAYMENT_DATE, STATUS_CODE)');
  ensure_index('IX_ONYX_PERIOD_SCOPE_DATES', 'CREATE INDEX IX_ONYX_PERIOD_SCOPE_DATES ON ONYX_FISCAL_PERIOD (COMPANY_ID, BRANCH_ID, START_DATE, END_DATE, STATUS_CODE)');
END;
/
COMMIT;
