-- يُنفذ تلقائيًا عند إنشاء الحاوية لأول مرة داخل XEPDB1.
-- لا تستخدم SYS أو SYSTEM في التطبيق.

ALTER SESSION SET CONTAINER = XEPDB1;

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER ONYX_LEGACY_STAGE IDENTIFIED BY "LegacyStage_ChangeMe_123"';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -01920 THEN RAISE; END IF;
END;
/

GRANT CREATE SESSION, RESOURCE TO ONYX_LEGACY_STAGE;
ALTER USER ONYX_LEGACY_STAGE QUOTA UNLIMITED ON USERS;

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER ONYX_APP IDENTIFIED BY "AppPassword_ChangeMe_123"';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -01920 THEN RAISE; END IF;
END;
/

GRANT CREATE SESSION TO ONYX_APP;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO ONYX_APP;
ALTER USER ONYX_APP QUOTA UNLIMITED ON USERS;
