[CmdletBinding()]
param(
  [string]$Output = "$(Join-Path $PSScriptRoot '..\data\mido-demo.accdb')",
  [switch]$Force,
  [string]$Provider = "Microsoft.ACE.OLEDB.16.0"
)

$ErrorActionPreference = 'Stop'
$Output = [IO.Path]::GetFullPath($Output)
$folder = Split-Path -Parent $Output
New-Item -ItemType Directory -Force -Path $folder | Out-Null
if ((Test-Path $Output) -and -not $Force) { throw "الملف موجود: $Output. استخدم -Force لإعادة إنشائه." }
if (Test-Path $Output) { Remove-Item -Force $Output }

function Quote-Sql([AllowNull()][string]$Value) {
  if ($null -eq $Value) { return 'NULL' }
  return "'" + $Value.Replace("'", "''") + "'"
}
function Date-Literal([datetime]$Value) { return "#$($Value.ToString('yyyy-MM-dd HH:mm:ss'))#" }

$providers = @($Provider, 'Microsoft.ACE.OLEDB.12.0') | Select-Object -Unique
$catalog = $null
$connectionString = $null
foreach ($candidate in $providers) {
  try {
    $catalog = New-Object -ComObject ADOX.Catalog
    $candidateString = "Provider=$candidate;Data Source=$Output;Jet OLEDB:Engine Type=6;"
    $catalog.Create($candidateString)
    $connectionString = $candidateString
    break
  } catch {
    if ($catalog) { [Runtime.InteropServices.Marshal]::ReleaseComObject($catalog) | Out-Null; $catalog = $null }
  }
}
if (-not $connectionString) {
  throw "تعذر إنشاء ملف Access. ثبّت Microsoft Access Database Engine 2016 (ACE 64-bit) أو استخدم -Provider Microsoft.ACE.OLEDB.12.0."
}

$conn = New-Object -ComObject ADODB.Connection
try {
  $conn.Open($connectionString)
  function Invoke-Sql([string]$Sql) {
    try { $null = $conn.Execute($Sql) }
    catch { throw "فشل SQL: $Sql`n$($_.Exception.Message)" }
  }

  $tables = @(
    "CREATE TABLE ONYX_SCHEMA_VERSION (VERSION_NO TEXT(20) NOT NULL, APPLIED_AT DATETIME NOT NULL)",
    "CREATE TABLE ONYX_COMPANY (COMPANY_ID LONG NOT NULL, COMPANY_CODE TEXT(30) NOT NULL, COMPANY_NAME_AR TEXT(200) NOT NULL, ACTIVE_FLAG INTEGER NOT NULL)",
    "CREATE TABLE ONYX_BRANCH (BRANCH_ID LONG NOT NULL, COMPANY_ID LONG NOT NULL, BRANCH_CODE TEXT(30) NOT NULL, BRANCH_NAME_AR TEXT(200) NOT NULL, ACTIVE_FLAG INTEGER NOT NULL)",
    "CREATE TABLE ONYX_FISCAL_YEAR (FISCAL_YEAR_ID LONG NOT NULL, COMPANY_ID LONG NOT NULL, YEAR_NO INTEGER NOT NULL, STATUS_CODE TEXT(20) NOT NULL)",
    "CREATE TABLE ONYX_FISCAL_PERIOD (PERIOD_ID LONG NOT NULL, COMPANY_ID LONG NOT NULL, BRANCH_ID LONG NOT NULL, FISCAL_YEAR_ID LONG NOT NULL, PERIOD_CODE TEXT(20) NOT NULL, PERIOD_NAME_AR TEXT(100) NOT NULL, START_DATE DATETIME NOT NULL, END_DATE DATETIME NOT NULL, STATUS_CODE TEXT(20) NOT NULL)",
    "CREATE TABLE ONYX_ACCOUNT (ACCOUNT_ID LONG NOT NULL, COMPANY_ID LONG NOT NULL, ACCOUNT_CODE TEXT(40) NOT NULL, ACCOUNT_NAME_AR TEXT(200) NOT NULL, ACCOUNT_TYPE TEXT(30) NOT NULL, PARENT_CODE TEXT(40), OPENING_BALANCE DECIMAL(19,4) NOT NULL, ACTIVE_FLAG INTEGER NOT NULL)",
    "CREATE TABLE ONYX_CONTACT (CONTACT_ID LONG NOT NULL, COMPANY_ID LONG NOT NULL, CONTACT_TYPE TEXT(20) NOT NULL, CODE TEXT(40) NOT NULL, NAME_AR TEXT(200) NOT NULL, PHONE TEXT(50), EMAIL TEXT(200), TAX_NUMBER TEXT(50), CREDIT_LIMIT DECIMAL(19,4), ACTIVE_FLAG INTEGER NOT NULL)",
    "CREATE TABLE ONYX_ITEM (ITEM_ID LONG NOT NULL, COMPANY_ID LONG NOT NULL, ITEM_CODE TEXT(40) NOT NULL, ITEM_NAME_AR TEXT(200) NOT NULL, UNIT_NAME TEXT(40), COST_PRICE DECIMAL(19,4) NOT NULL, SALE_PRICE DECIMAL(19,4) NOT NULL, QUANTITY DECIMAL(19,4) NOT NULL, REORDER_LEVEL DECIMAL(19,4) NOT NULL, ACTIVE_FLAG INTEGER NOT NULL)",
    "CREATE TABLE ONYX_WAREHOUSE (WAREHOUSE_ID LONG NOT NULL, COMPANY_ID LONG NOT NULL, BRANCH_ID LONG NOT NULL, WAREHOUSE_CODE TEXT(40) NOT NULL, WAREHOUSE_NAME TEXT(200) NOT NULL)",
    "CREATE TABLE ONYX_JOURNAL_ENTRY (ENTRY_ID LONG NOT NULL, COMPANY_ID LONG NOT NULL, BRANCH_ID LONG NOT NULL, FISCAL_YEAR_ID LONG NOT NULL, ENTRY_NO TEXT(40) NOT NULL, ENTRY_DATE DATETIME NOT NULL, DESCRIPTION_AR TEXT(500), STATUS_CODE TEXT(20) NOT NULL)",
    "CREATE TABLE ONYX_JOURNAL_LINE (LINE_ID LONG NOT NULL, ENTRY_ID LONG NOT NULL, ACCOUNT_ID LONG NOT NULL, LINE_DESCRIPTION_AR TEXT(500), DEBIT DECIMAL(19,4) NOT NULL, CREDIT DECIMAL(19,4) NOT NULL)",
    "CREATE TABLE ONYX_INVOICE (INVOICE_ID LONG NOT NULL, COMPANY_ID LONG NOT NULL, BRANCH_ID LONG NOT NULL, FISCAL_YEAR_ID LONG NOT NULL, INVOICE_TYPE TEXT(20) NOT NULL, INVOICE_NO TEXT(40) NOT NULL, CONTACT_ID LONG, SUBTOTAL DECIMAL(19,4) NOT NULL, TAX_AMOUNT DECIMAL(19,4) NOT NULL, TOTAL_AMOUNT DECIMAL(19,4) NOT NULL, PAID_AMOUNT DECIMAL(19,4) NOT NULL, OUTSTANDING_AMOUNT DECIMAL(19,4) NOT NULL, STATUS_CODE TEXT(20) NOT NULL, CURRENCY_CODE TEXT(10), EXCHANGE_RATE DECIMAL(19,6), INVOICE_DATE DATETIME NOT NULL)",
    "CREATE TABLE ONYX_INVOICE_LINE (LINE_ID LONG NOT NULL, INVOICE_ID LONG NOT NULL, ITEM_ID LONG NOT NULL, QUANTITY DECIMAL(19,4) NOT NULL, UNIT_PRICE DECIMAL(19,4) NOT NULL, LINE_TOTAL DECIMAL(19,4) NOT NULL)",
    "CREATE TABLE ONYX_STOCK_MOVEMENT (MOVEMENT_ID LONG NOT NULL, ITEM_ID LONG NOT NULL, WAREHOUSE_ID LONG NOT NULL, MOVEMENT_TYPE TEXT(30) NOT NULL, QUANTITY DECIMAL(19,4) NOT NULL, MOVEMENT_DATE DATETIME NOT NULL, SOURCE_NO TEXT(40))",
    "CREATE TABLE ONYX_USER (USER_ID LONG NOT NULL, USERNAME TEXT(100) NOT NULL, DISPLAY_NAME_AR TEXT(200) NOT NULL, PASSWORD_HASH TEXT(255) NOT NULL, ACTIVE_FLAG INTEGER NOT NULL)",
    "CREATE TABLE ONYX_ROLE (ROLE_ID LONG NOT NULL, ROLE_CODE TEXT(40) NOT NULL, ROLE_NAME_AR TEXT(200) NOT NULL)",
    "CREATE TABLE ONYX_USER_ROLE (USER_ID LONG NOT NULL, ROLE_ID LONG NOT NULL)",
    "CREATE TABLE ONYX_AUDIT_LOG (AUDIT_ID LONG NOT NULL, USERNAME TEXT(100), ACTION_CODE TEXT(50) NOT NULL, ENTITY_NAME TEXT(100), ENTITY_ID TEXT(50), CREATED_AT DATETIME NOT NULL)"
  )
  foreach ($table in $tables) { Invoke-Sql $table }

  $indexes = @(
    "CREATE UNIQUE INDEX UX_COMPANY_CODE ON ONYX_COMPANY (COMPANY_CODE)",
    "CREATE UNIQUE INDEX UX_BRANCH_CODE ON ONYX_BRANCH (COMPANY_ID, BRANCH_CODE)",
    "CREATE UNIQUE INDEX UX_ACCOUNT_CODE ON ONYX_ACCOUNT (COMPANY_ID, ACCOUNT_CODE)",
    "CREATE UNIQUE INDEX UX_CONTACT_CODE ON ONYX_CONTACT (COMPANY_ID, CODE)",
    "CREATE UNIQUE INDEX UX_ITEM_CODE ON ONYX_ITEM (COMPANY_ID, ITEM_CODE)",
    "CREATE INDEX IX_INVOICE_SCOPE_DATE ON ONYX_INVOICE (COMPANY_ID, BRANCH_ID, INVOICE_DATE)",
    "CREATE INDEX IX_INVOICE_NO ON ONYX_INVOICE (INVOICE_NO)",
    "CREATE INDEX IX_JOURNAL_SCOPE_DATE ON ONYX_JOURNAL_ENTRY (COMPANY_ID, BRANCH_ID, ENTRY_DATE)",
    "CREATE INDEX IX_AUDIT_CREATED ON ONYX_AUDIT_LOG (CREATED_AT)"
  )
  foreach ($index in $indexes) { Invoke-Sql $index }

  # Demo password: demo1234. PBKDF2-SHA256, compatible with access-db.js.
  $demoHash = 'pbkdf2$210000$demosalt$U-93sYVwC3d3rVh8JUuKheq85I5fp45PZ0hjWaCfgUE'
  $now = Get-Date
  Invoke-Sql "INSERT INTO ONYX_SCHEMA_VERSION VALUES ('access-demo-002', $(Date-Literal $now))"
  Invoke-Sql "INSERT INTO ONYX_COMPANY VALUES (1, 'DEMO', 'شركة ميدو التجريبية', 1)"
  Invoke-Sql "INSERT INTO ONYX_BRANCH VALUES (1, 1, 'MAIN', 'الفرع الرئيسي', 1)"
  Invoke-Sql "INSERT INTO ONYX_FISCAL_YEAR VALUES (1, 1, 2026, 'OPEN')"
  Invoke-Sql "INSERT INTO ONYX_FISCAL_PERIOD VALUES (1, 1, 1, 1, '2026-09', 'سبتمبر 2026', #2026-09-01#, #2026-09-30 23:59:59#, 'OPEN')"
  Invoke-Sql "INSERT INTO ONYX_USER VALUES (1, 'admin', 'مدير النظام', $(Quote-Sql $demoHash), 1)"
  Invoke-Sql "INSERT INTO ONYX_ROLE VALUES (1, 'ADMIN', 'مدير النظام')"
  Invoke-Sql "INSERT INTO ONYX_USER_ROLE VALUES (1, 1)"
  Invoke-Sql "INSERT INTO ONYX_ACCOUNT VALUES (1, 1, '1101', 'الصندوق', 'ASSET', NULL, 25000, 1)"
  Invoke-Sql "INSERT INTO ONYX_ACCOUNT VALUES (2, 1, '1201', 'العملاء', 'ASSET', NULL, 0, 1)"
  Invoke-Sql "INSERT INTO ONYX_ACCOUNT VALUES (3, 1, '4101', 'المبيعات', 'REVENUE', NULL, 0, 1)"
  Invoke-Sql "INSERT INTO ONYX_ACCOUNT VALUES (4, 1, '5101', 'تكلفة المبيعات', 'EXPENSE', NULL, 0, 1)"
  Invoke-Sql "INSERT INTO ONYX_CONTACT VALUES (1, 1, 'CUSTOMER', 'CUS-001', 'مؤسسة النور', '0500000000', 'sales@example.test', '300000000000003', 50000, 1)"
  Invoke-Sql "INSERT INTO ONYX_CONTACT VALUES (2, 1, 'VENDOR', 'VEN-001', 'شركة التوريد الحديثة', '0511111111', 'vendor@example.test', '300000000000004', 0, 1)"
  Invoke-Sql "INSERT INTO ONYX_ITEM VALUES (1, 1, 'ITEM-001', 'حاسوب محمول تجريبي', 'قطعة', 1800, 2500, 24, 5, 1)"
  Invoke-Sql "INSERT INTO ONYX_ITEM VALUES (2, 1, 'ITEM-002', 'شاشة مكتبية تجريبية', 'قطعة', 400, 650, 40, 10, 1)"
  Invoke-Sql "INSERT INTO ONYX_WAREHOUSE VALUES (1, 1, 1, 'MAIN', 'المستودع الرئيسي')"
  Invoke-Sql "INSERT INTO ONYX_STOCK_MOVEMENT VALUES (1, 1, 1, 'OPENING', 24, #2026-09-01#, 'OPENING-001')"
  Invoke-Sql "INSERT INTO ONYX_STOCK_MOVEMENT VALUES (2, 2, 1, 'OPENING', 40, #2026-09-01#, 'OPENING-001')"
  Invoke-Sql "INSERT INTO ONYX_INVOICE VALUES (1, 1, 1, 1, 'SALE', 'INV-1001', 1, 2500, 375, 2875, 1000, 1875, 'DRAFT', 'SAR', 1, #2026-09-01#)"
  Invoke-Sql "INSERT INTO ONYX_INVOICE_LINE VALUES (1, 1, 1, 1, 2500, 2500)"
  Invoke-Sql "INSERT INTO ONYX_AUDIT_LOG VALUES (1, 'admin', 'SEED_DEMO', 'DATABASE', '1', $(Date-Literal $now))"

  Write-Host "تم إنشاء قاعدة Access التجريبية: $Output"
  Write-Host "المزوّد: $Provider"
  Write-Host "بيانات الدخول: admin / demo1234"
} finally {
  if ($conn) { $conn.Close(); [Runtime.InteropServices.Marshal]::ReleaseComObject($conn) | Out-Null }
  if ($catalog) { [Runtime.InteropServices.Marshal]::ReleaseComObject($catalog) | Out-Null }
}
