param(
  [string]$Output = "$(Join-Path $PSScriptRoot '..\data\mido-demo.accdb')",
  [switch]$Force
)
$ErrorActionPreference = 'Stop'
$Output = [IO.Path]::GetFullPath($Output)
$folder = Split-Path -Parent $Output
New-Item -ItemType Directory -Force -Path $folder | Out-Null
if ((Test-Path $Output) -and -not $Force) { throw "الملف موجود: $Output. استخدم -Force لإعادة إنشائه." }
if (Test-Path $Output) { Remove-Item -Force $Output }

$catalog = New-Object -ComObject ADOX.Catalog
$connectionString = "Provider=Microsoft.ACE.OLEDB.16.0;Data Source=$Output;Jet OLEDB:Engine Type=6;"
$catalog.Create($connectionString)
$conn = New-Object -ComObject ADODB.Connection
$conn.Open($connectionString)

function Invoke-Sql([string]$Sql) { $null = $conn.Execute($Sql) }
function Q([string]$value) { if ($null -eq $value) { return 'NULL' }; return "'" + $value.Replace("'", "''") + "'" }

$tables = @(
"CREATE TABLE ONYX_SCHEMA_VERSION (VERSION_NO TEXT(20) NOT NULL, APPLIED_AT DATETIME NOT NULL)",
"CREATE TABLE ONYX_COMPANY (COMPANY_ID LONG NOT NULL, COMPANY_CODE TEXT(30) NOT NULL, COMPANY_NAME_AR TEXT(200) NOT NULL, ACTIVE_FLAG INTEGER NOT NULL)",
"CREATE TABLE ONYX_BRANCH (BRANCH_ID LONG NOT NULL, COMPANY_ID LONG NOT NULL, BRANCH_CODE TEXT(30) NOT NULL, BRANCH_NAME_AR TEXT(200) NOT NULL, ACTIVE_FLAG INTEGER NOT NULL)",
"CREATE TABLE ONYX_FISCAL_YEAR (FISCAL_YEAR_ID LONG NOT NULL, COMPANY_ID LONG NOT NULL, YEAR_NO INTEGER NOT NULL, STATUS_CODE TEXT(20) NOT NULL)",
"CREATE TABLE ONYX_ACCOUNT (ACCOUNT_ID LONG NOT NULL, COMPANY_ID LONG NOT NULL, ACCOUNT_CODE TEXT(40) NOT NULL, ACCOUNT_NAME_AR TEXT(200) NOT NULL, ACCOUNT_TYPE TEXT(30) NOT NULL, PARENT_CODE TEXT(40), OPENING_BALANCE DECIMAL(19,4) NOT NULL, ACTIVE_FLAG INTEGER NOT NULL)",
"CREATE TABLE ONYX_CONTACT (CONTACT_ID LONG NOT NULL, COMPANY_ID LONG NOT NULL, CONTACT_TYPE TEXT(20) NOT NULL, CODE TEXT(40) NOT NULL, NAME_AR TEXT(200) NOT NULL, PHONE TEXT(50), EMAIL TEXT(200), TAX_NUMBER TEXT(50), CREDIT_LIMIT DECIMAL(19,4), ACTIVE_FLAG INTEGER NOT NULL)",
"CREATE TABLE ONYX_ITEM (ITEM_ID LONG NOT NULL, COMPANY_ID LONG NOT NULL, ITEM_CODE TEXT(40) NOT NULL, ITEM_NAME_AR TEXT(200) NOT NULL, UNIT_NAME TEXT(40), COST_PRICE DECIMAL(19,4) NOT NULL, SALE_PRICE DECIMAL(19,4) NOT NULL, QUANTITY DECIMAL(19,4) NOT NULL, REORDER_LEVEL DECIMAL(19,4) NOT NULL, ACTIVE_FLAG INTEGER NOT NULL)",
"CREATE TABLE ONYX_JOURNAL_ENTRY (ENTRY_ID LONG NOT NULL, COMPANY_ID LONG NOT NULL, BRANCH_ID LONG NOT NULL, FISCAL_YEAR_ID LONG NOT NULL, ENTRY_NO TEXT(40) NOT NULL, ENTRY_DATE DATETIME NOT NULL, DESCRIPTION_AR TEXT(500), STATUS_CODE TEXT(20) NOT NULL)",
"CREATE TABLE ONYX_INVOICE (INVOICE_ID LONG NOT NULL, COMPANY_ID LONG NOT NULL, BRANCH_ID LONG NOT NULL, FISCAL_YEAR_ID LONG NOT NULL, INVOICE_TYPE TEXT(20) NOT NULL, INVOICE_NO TEXT(40) NOT NULL, CONTACT_ID LONG, SUBTOTAL DECIMAL(19,4) NOT NULL, TAX_AMOUNT DECIMAL(19,4) NOT NULL, TOTAL_AMOUNT DECIMAL(19,4) NOT NULL, PAID_AMOUNT DECIMAL(19,4) NOT NULL, OUTSTANDING_AMOUNT DECIMAL(19,4) NOT NULL, STATUS_CODE TEXT(20) NOT NULL, CURRENCY_CODE TEXT(10), EXCHANGE_RATE DECIMAL(19,6), INVOICE_DATE DATETIME NOT NULL)",
"CREATE TABLE ONYX_USER (USER_ID LONG NOT NULL, USERNAME TEXT(100) NOT NULL, DISPLAY_NAME_AR TEXT(200) NOT NULL, PASSWORD_HASH TEXT(255) NOT NULL, ACTIVE_FLAG INTEGER NOT NULL)",
"CREATE TABLE ONYX_ROLE (ROLE_ID LONG NOT NULL, ROLE_CODE TEXT(40) NOT NULL, ROLE_NAME_AR TEXT(200) NOT NULL)",
"CREATE TABLE ONYX_AUDIT_LOG (AUDIT_ID LONG NOT NULL, USERNAME TEXT(100), ACTION_CODE TEXT(50) NOT NULL, ENTITY_NAME TEXT(100), ENTITY_ID TEXT(50), CREATED_AT DATETIME NOT NULL)"
)
foreach ($table in $tables) { Invoke-Sql $table }

# Demo password: demo1234. The application verifies this PBKDF2 value.
$demoHash = 'pbkdf2$210000$demosalt$U-93sYVwC3d3rVh8JUuKheq85I5fp45PZ0hjWaCfgUE'
$now = Get-Date
Invoke-Sql "INSERT INTO ONYX_SCHEMA_VERSION VALUES ('access-demo-001', #$($now.ToString('yyyy-MM-dd HH:mm:ss'))#)"
Invoke-Sql "INSERT INTO ONYX_COMPANY VALUES (1, 'DEMO', 'شركة ميدو التجريبية', 1)"
Invoke-Sql "INSERT INTO ONYX_BRANCH VALUES (1, 1, 'MAIN', 'الفرع الرئيسي', 1)"
Invoke-Sql "INSERT INTO ONYX_FISCAL_YEAR VALUES (1, 1, 2026, 'OPEN')"
Invoke-Sql "INSERT INTO ONYX_USER VALUES (1, 'admin', 'مدير النظام', $(Q $demoHash), 1)"
Invoke-Sql "INSERT INTO ONYX_ROLE VALUES (1, 'ADMIN', 'مدير النظام')"
Invoke-Sql "INSERT INTO ONYX_ACCOUNT VALUES (1, 1, '1101', 'الصندوق', 'ASSET', NULL, 25000, 1)"
Invoke-Sql "INSERT INTO ONYX_ACCOUNT VALUES (2, 1, '4101', 'المبيعات', 'REVENUE', NULL, 0, 1)"
Invoke-Sql "INSERT INTO ONYX_CONTACT VALUES (1, 1, 'CUSTOMER', 'CUS-001', 'مؤسسة النور', '0500000000', 'sales@example.test', '300000000000003', 50000, 1)"
Invoke-Sql "INSERT INTO ONYX_CONTACT VALUES (2, 1, 'VENDOR', 'VEN-001', 'شركة التوريد الحديثة', '0511111111', 'vendor@example.test', '300000000000004', 0, 1)"
Invoke-Sql "INSERT INTO ONYX_ITEM VALUES (1, 1, 'ITEM-001', 'حاسوب محمول تجريبي', 'قطعة', 1800, 2500, 24, 5, 1)"
Invoke-Sql "INSERT INTO ONYX_ITEM VALUES (2, 1, 'ITEM-002', 'شاشة مكتبية تجريبية', 'قطعة', 400, 650, 40, 10, 1)"
Invoke-Sql "INSERT INTO ONYX_INVOICE VALUES (1, 1, 1, 1, 'SALE', 'INV-1001', 1, 2500, 375, 2875, 1000, 1875, 'DRAFT', 'SAR', 1, #2026-09-01#)"
Invoke-Sql "INSERT INTO ONYX_AUDIT_LOG VALUES (1, 'admin', 'SEED_DEMO', 'DATABASE', '1', #$($now.ToString('yyyy-MM-dd HH:mm:ss'))#)"
$conn.Close()
[Runtime.InteropServices.Marshal]::ReleaseComObject($conn) | Out-Null
[Runtime.InteropServices.Marshal]::ReleaseComObject($catalog) | Out-Null
Write-Host "تم إنشاء قاعدة Access التجريبية: $Output"
Write-Host "بيانات الدخول: admin / demo1234"
